-- ============================================
-- COLLEGE ERP SYSTEM
-- DATABASE TABLE CREATION
-- Oracle Database
-- ============================================

SET SQLBLANKLINES ON

-- ============================================
-- DROP EXISTING TABLES
-- ============================================

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE results CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE attendance CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE fees CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE notices CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE course CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE faculty CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE student CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE department CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- ============================================
-- DEPARTMENT TABLE
-- ============================================

CREATE TABLE department (
    department_id NUMBER PRIMARY KEY,
    department_name VARCHAR2(100) NOT NULL
);

-- ============================================
-- STUDENT TABLE
-- ============================================

CREATE TABLE student (
    student_id VARCHAR2(20) PRIMARY KEY,
    student_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100),
    phone VARCHAR2(15),
    department_id NUMBER,
    semester NUMBER,
    CONSTRAINT fk_student_department
        FOREIGN KEY (department_id)
        REFERENCES department(department_id)
);

-- ============================================
-- FACULTY TABLE
-- ============================================

CREATE TABLE faculty (
    faculty_id VARCHAR2(20) PRIMARY KEY,
    faculty_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100),
    department_id NUMBER,
    CONSTRAINT fk_faculty_department
        FOREIGN KEY (department_id)
        REFERENCES department(department_id)
);

-- ============================================
-- COURSE TABLE
-- ============================================

CREATE TABLE course (
    course_id VARCHAR2(20) PRIMARY KEY,
    course_name VARCHAR2(100) NOT NULL,
    department_id NUMBER,
    semester NUMBER,
    CONSTRAINT fk_course_department
        FOREIGN KEY (department_id)
        REFERENCES department(department_id)
);

-- ============================================
-- ATTENDANCE TABLE
-- ============================================

CREATE TABLE attendance (
    attendance_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR2(20) NOT NULL,
    course_id VARCHAR2(20) NOT NULL,
    attended_classes NUMBER DEFAULT 0,
    total_classes NUMBER DEFAULT 0,
    CONSTRAINT fk_attendance_student
        FOREIGN KEY (student_id)
        REFERENCES student(student_id),
    CONSTRAINT fk_attendance_course
        FOREIGN KEY (course_id)
        REFERENCES course(course_id),
    CONSTRAINT chk_attendance_values
        CHECK (
            attended_classes >= 0
            AND total_classes >= 0
            AND attended_classes <= total_classes
        )
);

-- ============================================
-- FEES TABLE
-- ============================================

CREATE TABLE fees (
    fee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR2(20) NOT NULL,
    total_fee NUMBER(10,2) DEFAULT 0,
    paid_fee NUMBER(10,2) DEFAULT 0,
    pending_fee NUMBER(10,2) DEFAULT 0,
    payment_status VARCHAR2(20),
    CONSTRAINT fk_fees_student
        FOREIGN KEY (student_id)
        REFERENCES student(student_id),
    CONSTRAINT chk_fee_values
        CHECK (
            total_fee >= 0
            AND paid_fee >= 0
            AND pending_fee >= 0
        )
);

-- ============================================
-- RESULTS TABLE
-- ============================================

CREATE TABLE results (
    result_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR2(20) NOT NULL,
    course_id VARCHAR2(20) NOT NULL,
    marks NUMBER(5,2),
    grade VARCHAR2(5),
    result_status VARCHAR2(20),
    CONSTRAINT fk_results_student
        FOREIGN KEY (student_id)
        REFERENCES student(student_id),
    CONSTRAINT fk_results_course
        FOREIGN KEY (course_id)
        REFERENCES course(course_id),
    CONSTRAINT chk_marks
        CHECK (marks >= 0 AND marks <= 100)
);

-- ============================================
-- NOTICES TABLE
-- ============================================

CREATE TABLE notices (
    notice_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200) NOT NULL,
    description VARCHAR2(1000),
    notice_date DATE DEFAULT SYSDATE
);

-- ============================================
-- USERS TABLE
-- ============================================

CREATE TABLE users (
    username VARCHAR2(50) PRIMARY KEY,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) NOT NULL,
    student_id VARCHAR2(20),
    CONSTRAINT fk_users_student
        FOREIGN KEY (student_id)
        REFERENCES student(student_id),
    CONSTRAINT chk_user_role
        CHECK (role IN ('STUDENT', 'FACULTY', 'ADMIN'))
);

COMMIT;

PROMPT ============================================
PROMPT COLLEGE ERP TABLES CREATED SUCCESSFULLY
PROMPT ============================================

SELECT table_name
FROM user_tables
WHERE table_name IN (
    'DEPARTMENT',
    'STUDENT',
    'FACULTY',
    'COURSE',
    'ATTENDANCE',
    'FEES',
    'RESULTS',
    'NOTICES',
    'USERS'
)
ORDER BY table_name;